name: Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install
        run: npm ci
      - name: Compile
        run: npm run compile
      - name: Lint
        run: npm run lint
      - name: Package vsix
        run: npx vsce package
      # - name: Test
      #   run: npm run test
